### PR TITLE
Zuhair Contribution

### PR DESCRIPTION
**Pull request by zuhairnaqi**
I've no hugo install

### CODE REVIEW

**Comment by zuhairnaqi** [comment]
This is my first contribution

**Comment by MovingToWeb** [comment]
Hi @zuhairnaqi You have to just create a *.md file with your details. I dont see this file in the Pull request

**Comment by zuhairnaqi** [comment]
Actually i've not installed hugo that's why i not added the file but now i
added the file but can't build the hugo.
I've send you merge request kindly merge my PR :)
Thank You

>

**Comment by MovingToWeb** [comment]
The PR says you have added a binary file?. Can you check the "Files Changed" section

**Pull request closed without merging**
